name: nonogram-qt # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.1.1' # just for humans, typically '1.2+git' or '1.3.2'
summary:  Nonogram-qt is a puzzle game that will generate (semi)random nonogram puzzles
description: |
   Nonogram-qt is a puzzle game that will generate (semi)random nonogram puzzles, and allow the user to
solve them. Please see https://en.wikipedia.org/wiki/Nonogram for more info on nonograms.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  nonogram-qt_icon.png
title: Nonogram QT

apps:
  nonogram-qt:
    command: nonogram-qt
parts:
  nonogram-qt:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      nonogram-qt: build/
      nonogram-qt.1: man/man1/

architectures:
  - build-on: amd64

